version: '2'
services:
  php-apache:
    image: dlvergara/php7.2.1-v1.0:latest
    ports:
      - 8081:80
    volumes:
      - ./app/:/var/www/html/
    environment:
      - MY_SERVER_NAME = localhost
      - APACHE_DOC_ROOT = /var/www/html/web
#      - "APACHE_DOCUMENT_ROOT=/var/www/html/web/"
#      - "sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf"
#      - "sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf"

#    links:
#      - 'mysql'
#  mysql:
#    image: mysql:5.6.40
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpassword