version: '2'
services:
  php-apache:
    image: dlvergara/php7.2.1-v1.0:latest
    ports:
      - 8081:80
    volumes:
      - ./app/:/var/www/html/
#    links:
#      - 'mysql'
#  mysql:
#    image: mysql:5.6.40
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpassword